In [5]:
import numpy as np

In [19]:
list1 = [123,561,-51,5125, True]

In [20]:
a = np.array(list1)

In [21]:
type(a)

numpy.ndarray

In [24]:
a

array([ 123,  561,  -51, 5125,    1])

In [25]:
# Slicing arrays

In [26]:
a[:2]

array([123, 561])

In [30]:
# Need to use copy to create a new copy of an array. If not changes in b will make changes in a...!
b = a.copy()

In [28]:
a

array([ 123,  561,  -51, 5125,    1])

In [29]:
b

array([ 123,  561,  -51, 5125,    1])